### PR TITLE
Aimbo hometown

### PR DESCRIPTION
**Pull request by acedubs**
ssh://master.kernel.org/pub/scm/linux/kernel/git/sam/kbuild-fixes.git
Kconfig: introduce ARCH_DEFCONFIG to DEFCONFIG_LIST

.gitignore | 1 / !1 /0
arch/x86/Kconfig | 13 ***----------
init/Kconfig | 1 (×)
scripts/ver_linux | 5 (×)----
4 files changed, 6 insertions(+), 14 deletions(-)
.gitignore: match ncscope.pout
scripts/ver_linux use 'gcc -dumpversion'
diff --git a/.gitignore b/.gitignore
index 9c0d650..d24ad50 100644
--- a/.gitignore
+++ b/.gitignore
@@ -52,6 +52,7 @@ series
# cscope files

cscope.*
+ncscope.*

*.orig
*~
diff --git a/arch/x86/Kconfig b/arch/x86/Kconfig
index fe361ae..dcbec1134 100644
--- a/arch/x86/Kconfig http://goo.gl/SzjbYr

### CODE REVIEW

**Comment by brianamarie** [comment]
@acedubs Hi! Can you help me understand what you pasted here?

**Comment by acedubs** [comment]
::directives for google-charts mine .dmp cots [bash]

**Comment by acedubs** [comment]
google.com/_/chrome/newtab?espv=2&ie=UTF-8 wifi on univercitibank-bands.js

**Comment by acedubs** [comment]
https://bash.cyberciti.biz/web-server/rhel-fedora-php-fastcgi-initd-script/ #hears a manuals..$

**Comment by acedubs** [comment]
git merge --abort [does this undo mrgr] ??

**Comment by brianamarie** [comment]
@acedubs I think you're trying to use command line syntax - none of that is necessary for what we're covering in today's class. If you're interested, we will get into things like `git merge --abort` in the GitHub for developers class found here: https://services.github.com/training/

**Pull request merged**
