### PR TITLE
Siamak amiri belfast

### PR DESCRIPTION
**Pull request by SiamakAmiri**

### CODE REVIEW

**Comment by brianamarie** [comment]
@SiamakAmiri What are some of your favorite restaurants?

**Comment by SiamakAmiri** [comment]
Indian

**Comment by SiamakAmiri** [comment]
Indian

**Comment by SiamakAmiri** [comment]
# Indian

**Comment by SiamakAmiri** [comment]
- Indian

**Comment by SiamakAmiri** [comment]
# Restaurants
- Indian

**Pull request merged**
